cpf = input("CPF")
nome = input("Nome")
celular = input("Celular")
logradouro = input("Logradouro")
numero = input("Numero")
complemento = input("Complemento")
bairro = input("bairro")
cidade = input("Cidade")
estado = input("estado")
cep = input("CEP")
print("{}.{}.{}-{}".format(cpf[:3],cpf[3:6],cpf[6:9],cpf[9:]))
print(nome)
print("({}) {}-{}".format(celular[:2],celular[2:7],celular[7:]))
print(logradouro)
print(numero)
print(complemento)
print(bairro)
print(cidade)
print(estado)
print("{}.{}-{}".format(cep[:2],cep[2:5],cep[5:]))

