cpf = input("CPF")
nome = input("Nome")
celular = input("Celular")
logradouro = input("Logradouro")
numero = input("Numero")
complemento = input("Complemento")
bairro = input("bairro")
cidade = input("Cidade")
estado = input("estado")
cep = input("CEP")
print(cpf)
print(nome)
print(celular)
print(logradouro)
print(numero)
print(complemento)
print(bairro)
print(cidade)
print(estado)
print(cep)

